//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analytics
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIDDATA
    {
        public int PK_Uid { get; set; }
        public string ReferenceNumber { get; set; }
        public string Longurl { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    }
}
